apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-n4ff
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-n4ff
    app.kubernetes.io/part-of: cin4s-839-0061-app
  name: devfile-sample-n4ff
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-n4ff
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-n4ff
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0061-tenant/cin4s-839-0061-app/devfile-sample-n4ff@sha256:c5de508335144bc9f000669f57521586a385f400bb292db61c046990ed1927cf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
